/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kopytka.avro.customer;
@org.apache.avro.specific.AvroGenerated
public enum CustomerEventType implements org.apache.avro.generic.GenericEnumSymbol<CustomerEventType> {
  CREATED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CustomerEventType\",\"namespace\":\"pl.kopytka.avro.customer\",\"symbols\":[\"CREATED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
