spring:
  application:
    name: "gateway"

server:
  port: 9000

eureka:
  instance:
    preferIpAddress: true  # Preferuj używanie adresu IP zamiast nazwy hosta podczas rejestracji usługi w Eureka
  client:
    fetchRegistry: true    # Pozwala na pobieranie rejestru usług z serwera Eureka, umożliwiając odnajdywanie innych usług
    registerWithEureka: true  # Rejestruje tę usługę w serwerze Eureka, aby inne serwisy mogły ją odnaleźć
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  # Adres URL serwera Eureka, do którego usługa się rejestruje i z którego pobiera informacje o innych usługach

