spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
 #   show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
  datasource:
    url: jdbc:h2:mem:kopytkadb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

payment-service:
  reprocess-payments:
    interval-in-seconds: 300  # Run every 5 minutes
    reprocess-scheduler:
      lock-at-most-for: 10m     # Maximum lock duration
      lock-at-least-for: 4m     # Minimum lock duration

server:
  port: 8582

eureka:
  instance:
    preferIpAddress: true  # Preferuj używanie adresu IP zamiast nazwy hosta podczas rejestracji usługi w Eureka
  client:
    fetchRegistry: true    # Pozwala na pobieranie rejestru usług z serwera Eureka, umożliwiając odnajdywanie innych usług
    registerWithEureka: true  # Rejestruje tę usługę w serwerze Eureka, aby inne serwisy mogły ją odnaleźć
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  # Adres URL serwera Eureka, do którego usługa się rejestruje i z którego pobiera informacje o innych usługach