/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kopytka.avro.restaurant;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RestaurantOrderApprovedAvroEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4022646105740271979L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RestaurantOrderApprovedAvroEvent\",\"namespace\":\"pl.kopytka.avro.restaurant\",\"fields\":[{\"name\":\"restaurantId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<RestaurantOrderApprovedAvroEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RestaurantOrderApprovedAvroEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RestaurantOrderApprovedAvroEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RestaurantOrderApprovedAvroEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RestaurantOrderApprovedAvroEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RestaurantOrderApprovedAvroEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RestaurantOrderApprovedAvroEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RestaurantOrderApprovedAvroEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RestaurantOrderApprovedAvroEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID restaurantId;
  private java.util.UUID orderId;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RestaurantOrderApprovedAvroEvent() {}

  /**
   * All-args constructor.
   * @param restaurantId The new value for restaurantId
   * @param orderId The new value for orderId
   * @param createdAt The new value for createdAt
   */
  public RestaurantOrderApprovedAvroEvent(java.util.UUID restaurantId, java.util.UUID orderId, java.time.Instant createdAt) {
    this.restaurantId = restaurantId;
    this.orderId = orderId;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return restaurantId;
    case 1: return orderId;
    case 2: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: restaurantId = (java.util.UUID)value$; break;
    case 1: orderId = (java.util.UUID)value$; break;
    case 2: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'restaurantId' field.
   * @return The value of the 'restaurantId' field.
   */
  public java.util.UUID getRestaurantId() {
    return restaurantId;
  }


  /**
   * Sets the value of the 'restaurantId' field.
   * @param value the value to set.
   */
  public void setRestaurantId(java.util.UUID value) {
    this.restaurantId = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.util.UUID getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.util.UUID value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new RestaurantOrderApprovedAvroEvent RecordBuilder.
   * @return A new RestaurantOrderApprovedAvroEvent RecordBuilder
   */
  public static pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder newBuilder() {
    return new pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder();
  }

  /**
   * Creates a new RestaurantOrderApprovedAvroEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RestaurantOrderApprovedAvroEvent RecordBuilder
   */
  public static pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder newBuilder(pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder other) {
    if (other == null) {
      return new pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder();
    } else {
      return new pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder(other);
    }
  }

  /**
   * Creates a new RestaurantOrderApprovedAvroEvent RecordBuilder by copying an existing RestaurantOrderApprovedAvroEvent instance.
   * @param other The existing instance to copy.
   * @return A new RestaurantOrderApprovedAvroEvent RecordBuilder
   */
  public static pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder newBuilder(pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent other) {
    if (other == null) {
      return new pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder();
    } else {
      return new pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RestaurantOrderApprovedAvroEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RestaurantOrderApprovedAvroEvent>
    implements org.apache.avro.data.RecordBuilder<RestaurantOrderApprovedAvroEvent> {

    private java.util.UUID restaurantId;
    private java.util.UUID orderId;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[0].schema(), other.restaurantId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RestaurantOrderApprovedAvroEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[0].schema(), other.restaurantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderId)) {
        this.orderId = data().deepCopy(fields()[1].schema(), other.orderId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[2].schema(), other.createdAt);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'restaurantId' field.
      * @return The value.
      */
    public java.util.UUID getRestaurantId() {
      return restaurantId;
    }


    /**
      * Sets the value of the 'restaurantId' field.
      * @param value The value of 'restaurantId'.
      * @return This builder.
      */
    public pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder setRestaurantId(java.util.UUID value) {
      validate(fields()[0], value);
      this.restaurantId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantId' field has been set.
      * @return True if the 'restaurantId' field has been set, false otherwise.
      */
    public boolean hasRestaurantId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'restaurantId' field.
      * @return This builder.
      */
    public pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder clearRestaurantId() {
      restaurantId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.util.UUID getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder setOrderId(java.util.UUID value) {
      validate(fields()[1], value);
      this.orderId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public pl.kopytka.avro.restaurant.RestaurantOrderApprovedAvroEvent.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RestaurantOrderApprovedAvroEvent build() {
      try {
        RestaurantOrderApprovedAvroEvent record = new RestaurantOrderApprovedAvroEvent();
        record.restaurantId = fieldSetFlags()[0] ? this.restaurantId : (java.util.UUID) defaultValue(fields()[0]);
        record.orderId = fieldSetFlags()[1] ? this.orderId : (java.util.UUID) defaultValue(fields()[1]);
        record.createdAt = fieldSetFlags()[2] ? this.createdAt : (java.time.Instant) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RestaurantOrderApprovedAvroEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RestaurantOrderApprovedAvroEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RestaurantOrderApprovedAvroEvent>
    READER$ = (org.apache.avro.io.DatumReader<RestaurantOrderApprovedAvroEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










