/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kopytka.avro.restaurant;
@org.apache.avro.specific.AvroGenerated
public enum RestaurantEventType implements org.apache.avro.generic.GenericEnumSymbol<RestaurantEventType> {
  ORDER_APPROVED, ORDER_REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RestaurantEventType\",\"namespace\":\"pl.kopytka.avro.restaurant\",\"symbols\":[\"ORDER_APPROVED\",\"ORDER_REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
