/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kopytka.avro.restaurant;
@org.apache.avro.specific.AvroGenerated
public enum RestaurantCommandType implements org.apache.avro.generic.GenericEnumSymbol<RestaurantCommandType> {
  APPROVE_ORDER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RestaurantCommandType\",\"namespace\":\"pl.kopytka.avro.restaurant\",\"symbols\":[\"APPROVE_ORDER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
