/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kopytka.avro.payment;
@org.apache.avro.specific.AvroGenerated
public enum PaymentEventType implements org.apache.avro.generic.GenericEnumSymbol<PaymentEventType> {
  PAYMENT_COMPLETED, PAYMENT_CANCELLED, PAYMENT_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentEventType\",\"namespace\":\"pl.kopytka.avro.payment\",\"symbols\":[\"PAYMENT_COMPLETED\",\"PAYMENT_CANCELLED\",\"PAYMENT_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
