/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.kopytka.avro.payment;
@org.apache.avro.specific.AvroGenerated
public enum PaymentCommandType implements org.apache.avro.generic.GenericEnumSymbol<PaymentCommandType> {
  CREATE_PAYMENT, CANCEL_PAYMENT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentCommandType\",\"namespace\":\"pl.kopytka.avro.payment\",\"symbols\":[\"CREATE_PAYMENT\",\"CANCEL_PAYMENT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
